// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6zJXoOXHQepZy89Z1mQomSRUacHX-6h0',
    appId: '1:226707394666:web:344f179edead402fa8fa13',
    messagingSenderId: '226707394666',
    projectId: 'mc-flutter-project-6a5ca',
    authDomain: 'mc-flutter-project-6a5ca.firebaseapp.com',
    storageBucket: 'mc-flutter-project-6a5ca.firebasestorage.app',
    measurementId: 'G-4G6LHM6HYE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD15DZL7ADStaot3-tPlCjssW01cofJriw',
    appId: '1:226707394666:android:91f9fc6e28adb751a8fa13',
    messagingSenderId: '226707394666',
    projectId: 'mc-flutter-project-6a5ca',
    storageBucket: 'mc-flutter-project-6a5ca.firebasestorage.app',
  );
}
